version: '3.8'

services:
  valkey:
    image: valkey/valkey:9-alpine
    ports:
      - 6379:6379
    command: valkey-server /usr/local/etc/valkey/valkey.conf
    volumes:
      - ./valkey/data:/data
      - ./valkey/conf/valkey.conf:/usr/local/etc/valkey/valkey.conf
    labels:
      - 'name=valkey'
      - 'mode=standalone'
    restart: always
